id: AEA2290A8
title: Prayer for the Long Life of Lochen Ngawang Chöpal
type: translation
pechas:
- I2CA3AAD2
- IB3A36137
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:58:12.959826
  last_modified_at: 2023-01-04 12:58:12.959846
  collections:
  - Lochen Dharmaśrī Series
  - Works of Tibetan Masters
alignment_to_base:
  I2CA3AAD2/9989: 3F83
  IB3A36137/4EA1: 3F83
